### ISSUE TITLE
Does it work for NES save files?

### ISSUE THREAD

**Issue by edrozenberg** [superg/srmtools#1]
Thanks for these tools.

I used save2srm to convert an NES MiSTer savefile (.sav) to EverDrive format (srm).

The original file .sav was 32 KB, and the new converted srm file shows as 65 KB.

 But on EverDrive N8 Pro, normal NES savegames are 8 KB.

So not sure if this tool works for NES games.

**Comment by superg** [comment]
That was a quickie util requested by Bob@RetroRGB. I didn't check NES at all, if you can provide both N8 and MiSTer savegame examples for the same game I can check that out later and maybe implement (quite busy ATM).

**Comment by edrozenberg** [comment]
@superg I appreciate it! 

Attaching `Zelda 1.sav` (MiSTer) and `Zelda 1.srm` (EverDrive N8 Pro). Different saves from different points in the game (so not exactly equivalent).

After a lot of searching I didn't find any solution for NES so far. I found a reference to these tools for MegaDrive (Sega Genesis):
https://krikzz.com/pub/support/everdrive-md/v2/8to16.exe
https://krikzz.com/pub/support/everdrive-md/v2/16to8.exe

[Zelda 1.sav.zip](https://github.com/superg/srmtools/files/6138216/Zelda.1.sav.zip)
[Zelda 1.srm.zip](https://github.com/superg/srmtools/files/6138217/Zelda.1.srm.zip)

**Comment by superg** [comment]
Took a while to get back to it, sorry about that.
So these two saves are identical except SAV is padded with zeroes, this is trivial to implement, save2srm has to trim the excess zeroes, the reverse srm2save is to pad.
I'm not familiar with MiSTer, is it always 32Kb savestate for NES?

**Comment by edrozenberg** [comment]
@superg thanks - I see one that is 130 KB.

In case it helps, my MiSTer saves/savestates:
[MiSTer saves.zip](https://github.com/superg/srmtools/files/6872734/MiSTer.saves.zip)
[MiSTer savestates.zip](https://github.com/superg/srmtools/files/6872735/MiSTer.savestates.zip)

**Comment by superg** [comment]
Thanks for the samples. I see, so MiSTer save state specs really depend on a system core.
It's possible that you will be able to use NES MiSTer save states on EverDrive just by renaming *.sav to *.srm, did you try that?

**Comment by edrozenberg** [comment]
It doesn't work but thanks for letting me know. I'll anyway just use my MiSTer most of the time.

**Comment by superg** [comment]
I can actually quickly add pad and trim if you think it's useful - let me know.

**Comment by edrozenberg** [comment]
It's ok probably not worth the effort unless other people ask for it. MiSTer is working very well for me so don't have much need to switch to the Analogue console anytime soon. Thanks again.
